# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4d1b8c70-be56-41d4-bd4e-484c286a2900";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."enc-pv".device = "/dev/disk/by-uuid/111ac5c4-a6ce-41d8-bf8e-d0a5e454930c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2996-47BB";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bba21507-7811-4e22-8edf-deeaa91d73fb"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
